### ISSUE TITLE
removing a device your device list should remove it from notification targets also

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-meta#1216]
see https://matrix.to/#/!cURbafjkfsMDVwdRDQ:matrix.org/$148958044318704QYVVV:matrix.org

**Comment by lampholder** [comment]
> krombel: i removed the devices but there are still two entries in my "NOTIFICATION TARGETS", one for the old and one for the new phone.

Seems like a legitimate ask. I suspect this is a duplicate of vector-im/element-web#2304.

Probably best resolved by adding a 'remove' option to the NOTIFICATION TARGETS section of the settings page _and_ by autoremoving any associated notification targets when a device is removed from the DEVICES list.

**Comment by daniellekirkwood** [comment]
i just tested this and confirm that it works as expected. closing - re-open if it's still an issue and I missed something.

**Comment by nyabinary** [comment]
> i just tested this and confirm that it works as expected. closing - re-open if it's still an issue and I missed something.

Doesn't seem to work when singing out of Element X, I signed out of Element X on my Android phone and the notification target was not cleared.
