### ISSUE TITLE
Implement a less obtrusive indication of message editing

### ISSUE THREAD

**Issue by Shaping** [element-hq/element-meta#1544]
'(edited)' is currently postfixed at the end of an edited message.   Can we make this less clunky and more visually attractive by having the option of using color instead of the parenthetical text (which could be the default)?   We could have a colored background for each message (which is useful anyway for finding message boundaries quickly), as Telegram does, and then color the border blue (or whatever--make it user-selectable) for edited messages.  Use hover-text at the has-been-edited colored boundary to show the number of times the message has been edited, and let the context menu there access the edit-history.

**Comment by ara4n** [comment]
sorry; we like the current UI.
