### ISSUE TITLE
Prohibit the use / commands

### ISSUE THREAD

**Issue by SiriusGale** [element-hq/element-meta#1663]
#### Is your suggestion related to a problem? Please describe.
We are trying to use Matrix + Element-Web like our company environment and we have some policy about user naming
Only administrators should have a permission to change it
We have own Matrix homeserver and Element-Web server 

In Matrix homeserver.yaml we have:
`enable_set_displayname: false`

But users can still change it via chat command:
`/myroomnick <>`

#### Describe the solution you'd like.
So it will be great to have a opportunity to prohibit the use this and any other / commands

**Comment by richvdh** [comment]
This doesn't seem like something we would implement. As @t3chguy says, any client side measure is trivially circumvented.
