### ISSUE TITLE
Consider changing block/blacklist device to be "reject device", with associated UX improvements

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-meta#2652]
The word 'blacklist' is still not entirely working for me - it feels too jargony and still contains massive connotations of stopping you from receiving messages rather than sending them.

I wonder if "reject device" might be better - especially in the context of the new warn-unknown-device stuff, where you would then get warnings of the form "Someone has added a new device to the room - do you want to reject it?"

I'm also wondering if this idiom could then potentially entirely replace the blacklist-unverified config options which I PR'd last night (https://github.com/matrix-org/matrix-react-sdk/pull/636).  Currently this provides checkboxes in UserSettings & RoomSettings to enable "blacklist unverified" mode.  Perhaps this is unnecessary and needlessly hidden, though, as if the UnknownDeviceDialog went and just had a button for "reject all unverified devices" at the bottom it might be unnecessary - making the user spell out whether to reject for new devices (but positioning it almost as the default option).

This would then gather all the device trust management into a single dashboard dialog, so when new devices are added into a room, you'd get the dialog, but it would:

 * Show *all* the unverified devices in the room (and possibly the verified ones too for completeness) - rather than the subset of just 'unknown' ones we show atm?  This gives the user better visibility and also keeps reminding them which unverified devices they hanging around.
 * Give the option to bulk-reject in a room every time new devices come up.  It's not /quite/ as safe as silently that without prompting the user, but it's a bit more predictable and less magical.

@richvdh wdyt?

**Comment by richvdh** [comment]
We're removing/have removed this bit of UI altogether
