### ISSUE TITLE
Structured logging on clients (opentracing compatible)

### ISSUE THREAD

**Issue by BillCarsonFr** [element-hq/element-meta#32]
First step for: https://github.com/vector-im/element-meta/issues/31

**Goal**
Improve the logging in general
Switch to structured logging and a common output format for those logs \(e.g. opentracing compatible\)
Improve the experience when going through rageshakes, if our shakes are opentracing compatible we could use jaeger to inspect/search through them

- \[ \] #40
- \[ \] Implement on web
- \[ \] Implement on iOS
- \[ \] Implement on Android

**Comment by richvdh** [comment]
Duplicate of https://github.com/element-hq/crypto-internal/issues/132 (which has been closed as "not planned")
